### PR TITLE
new Storage Cmdlets

### PR DESCRIPTION
**Pull request by shiller79**
new Cmdlets:
Add-Storage
Remove-Storage
Enable-Storage
Disable-Storage
Get-Storage

### CODE REVIEW

**Comment by agonzalezm** [comment]
Hi @shiller79 , great to see your pull requests!

One comment, you are specifying all properties for formatuebresult:

$prop = @('id','is_pending','request_id','name','host','asset_tag','role',
-          'version','version_status','local','total_mb_size','total_mb_free',
-          'archiving','replicating','online','status','message','created','updated')
-   
-      FormatUebResult $obj $prop

The idea of FormatUebResult is to show result in a nice formatted table, but we cant show more than 4 properties in table format so I usually specify there only the main 4 properties of the object that we want to show.

All the properties for the object are returned and accessible anyway dont need to specify there.

I think for end users is better if all commands return in same format, as long list make it difficult to read. what do you think?

As sample if you just use get-uebjob it will show you all jobs and  their 4 main prop in table/columns

PS > get-uebjob

name        type          last_status status

---

Backup Job  backup        Success     Idle
Exchange01  backup        Never       Idle
dc          backup        Success     Idle

But you can explore all properties using Format-Table or Select-Object

PS > get-uebjob | fl *
sid              : 1
id               : 1b
name             : Backup Job
type             : backup
app_id           : 40
system_name      : ueb08
description      : Backup Job
enabled          : 1
last_time        : 03/08/2016 03:00:00 am
next_time        : 03/09/2016 03:00:00 am
last_status      : Success
status           : Idle
calendar_str     : {Full: Sun-Sat at 03:00:00 am}
application_name : VMware

sid              : 1
id               : 3b
name             : Exchange01
type             : backup
app_id           : 40
system_name      : ueb08
description      : Exchange01
enabled          : 1
last_time        : 03/08/2016 03:00:00 am
next_time        : 03/09/2016 03:00:00 am
last_status      : Never
status           : Idle
calendar_str     : {Incremental: Sun-Sat at 03:00:00 am}
application_name : VMware

or select which properties to show using select-object

PS> get-uebjob | Select-Object name,last_time

Thanks,
Alberto

**Comment by shiller79** [comment]
Hi Alberto,

Thanks for your suggestion. You are right, it’s better to see the result in a table. I have reduce the properties.

Greeting
Sascha

**Comment by agonzalezm** [comment]
Thanks Sascha! I am going to merge this if you dont have more changes.

BTW, could you join the gitter chat room (https://gitter.im/Unitrends/unitrends-pstoolkit) or drop me a message?

We are going to create a blog post about unitrends powershell community and would like to know your name, company, etc to give you some credit as you have done the first non-unitrends pull request and also know why did you choose to work on these cmdlets? What are you trying to automate/solve/ etc with *storage cmdlets?

We will also announce a contest where top external contributors commiting new cmdlets, bugs, ideas, blogs etc during next 3 months will be rewarded with an amazon gift card. 

Thanks,
Alberto

**Comment by shiller79** [comment]
Hi Alberto,
English isn’t my first language, so please excuse any mistakes.
My name is Sascha Hiller, I work for „Binder IT-Systemhaus GmbH“ (www.binder-it.de) a small IT-Company in Sindelfingen, Germany as system administrator. I’m not a Developer so this is my first Pull request, too.

A few weeks ago I attend to a Unitrends training with Rainer Kalthoff. He shows us how to use the REST-Api and the Powershell Toolkit.

My customers wants to have a monthly backup that can be taken to a safe deposit box. So I have to disable the Backup Copy Target when the disk is offline and enable it when it returns from the bank. I want to automate this task, but there was no Cmdlet in the Powershell Toolbox to do this. That's why I decided to write the missing Cmdlet and created this Pull request to share it with other users of UEB. 

Sascha

**Comment by agonzalezm** [comment]
Thanks Sascha for the info! have merged this

**Pull request merged**
